"use client";

import { useEffect, useRef, useState, useTransition } from "react";
import { toast } from "sonner";
import { formatRelative } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { reviewCounterDraft, approveWithVariant, publishDraft } from "@/app/actions/counter-draft";
import { triggerSimulator } from "@/app/actions/simulator";
import { sourceMeta } from "@/components/dashboard/signal-card";

type Draft = {
  id: string;
  signal_id: string | null;
  status: "draft" | "approved" | "rejected" | "published";
  body: string;
  channel_hint: "x" | "linkedin" | "blog" | "multi";
  tone_pillar: string;
  reasoning: string;
  evidence_refs: string[];
  created_at: string;
};

type ContentVariant = {
  id: string;
  channel: "blog" | "x_thread" | "linkedin";
  title: string | null;
  body: string;
  status?: "generated" | "edited" | "sent" | "archived";
};

type Signal = {
  id: string;
  severity: "low" | "med" | "high";
  sentiment: "positive" | "neutral" | "negative";
  summary: string;
  source_type: "competitor" | "internal" | "external" | "peec_delta";
};

type PhraseAvailability = {
  taken: boolean;
  by: string[];
  evidence_urls: string[];
};

type JudgeDimensions = {
  specificity: number;
  brand_voice: number;
  persuasiveness: number;
  differentiation: number;
};

type NarrativeVariant = {
  id: string;
  rank: number;
  body: string;
  score: number;
  predicted_sentiment: "positive" | "neutral" | "negative";
  avg_position: number | null;
  mention_rate: number;
  metadata?: {
    phrase_availability?: PhraseAvailability;
    lift_vs_baseline?: number | null;
    // New judge-based fields (post-2026-04-26 refactor). Older rows persisted
    // before the refactor will not have these — UI falls back to `score`.
    angle?: string;
    angle_label?: string;
    forbidden_retry_count?: number;
    judge_score?: number; // 1-10
    judge_reasoning?: string;
    judge_dimensions?: JudgeDimensions;
    set_diversity_score?: number; // 1-10, same value across all rows in a run
    set_diversity_reasoning?: string;
  } | null;
};

const severityChip: Record<Signal["severity"], string> = {
  high: "bg-red-100 text-red-800 dark:bg-red-950 dark:text-red-300",
  med: "bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300",
  low: "bg-zinc-100 text-zinc-700 dark:bg-zinc-800 dark:text-zinc-300",
};

const sentimentEmoji: Record<NarrativeVariant["predicted_sentiment"], string> = {
  positive: "🙂",
  neutral: "😐",
  negative: "🙁",
};

function channelLabel(c: ContentVariant["channel"]): string {
  switch (c) {
    case "blog":
      return "📝 Blog";
    case "x_thread":
      return "🐦 X thread";
    case "linkedin":
      return "💼 LinkedIn";
  }
}

const statusColor: Record<string, string> = {
  draft: "bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300",
  approved: "bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300",
  rejected: "bg-zinc-200 text-zinc-700 dark:bg-zinc-800 dark:text-zinc-300",
  published: "bg-blue-100 text-blue-800 dark:bg-blue-950 dark:text-blue-300",
};

const stageTooltip: Record<string, string> = {
  Signal: "Detected by W9 competitor radar (Peec delta або Tavily search)",
  Draft: "Counter-narrative generated by LLM з brand voice",
  Approve: "Manual review · approve тригерить W7 expand event",
  Expand: "W7 generates 3 channel variants: blog / X / LinkedIn",
  Publish: "Mark variant as published у content_variants.status",
};

function DraftStepper({
  status,
  variantsCount,
}: {
  status: "draft" | "approved" | "rejected" | "published";
  variantsCount: number;
}) {
  // Stage states: 0 done, 1 active, 2 pending, 3 skipped
  const isRejected = status === "rejected";
  const stages: Array<{ label: string; state: 0 | 1 | 2 | 3 }> = [
    { label: "Signal", state: 0 },
    { label: "Draft", state: 0 },
    {
      label: "Approve",
      state: isRejected ? 3 : status === "draft" ? 1 : 0,
    },
    {
      label: "Expand",
      state: isRejected ? 3 : variantsCount === 0 ? (status === "approved" ? 1 : 2) : 0,
    },
    {
      label: "Publish",
      state: isRejected ? 3 : status === "published" ? 0 : variantsCount > 0 ? 1 : 2,
    },
  ];

  const stateClass = (s: 0 | 1 | 2 | 3): string => {
    if (s === 0) return "bg-emerald-500 text-white";
    if (s === 1) return "bg-primary text-primary-foreground ring-2 ring-primary/30";
    if (s === 3) return "bg-zinc-200 text-zinc-500 dark:bg-zinc-800 line-through";
    return "bg-secondary text-muted-foreground";
  };

  return (
    <ol className="mt-2 flex items-center gap-1 overflow-x-auto text-[10px] uppercase tracking-wider">
      {stages.map((s, i) => (
        <li key={s.label} className="flex items-center gap-1">
          <span
            className={`flex h-5 cursor-help items-center rounded-full px-2 ${stateClass(s.state)}`}
            title={stageTooltip[s.label]}
          >
            {s.state === 0 ? "✓" : s.state === 3 ? "✗" : i + 1} <span className="ml-1">{s.label}</span>
          </span>
          {i < stages.length - 1 ? (
            <span className="h-px w-3 shrink-0 bg-border" aria-hidden />
          ) : null}
        </li>
      ))}
    </ol>
  );
}

export function DraftCard({
  draft,
  variants,
  signal,
  narrativeVariants,
  organizationId,
  brandSlug,
  decided,
}: {
  draft: Draft;
  variants: ContentVariant[];
  signal: Signal | null;
  narrativeVariants: NarrativeVariant[];
  organizationId: string;
  brandSlug: string;
  decided?: boolean;
}) {
  const [isPending, startTransition] = useTransition();
  const [optimisticStatus, setOptimisticStatus] = useState(draft.status);
  // Compact mode default: collapsed everything except meta + CTA. Click chevron — full layout.
  const [expanded, setExpanded] = useState(false);

  // Track in-flight async operations щоб показати inline progress.
  // Baselines зберігають кількість variants на момент кліку — коли real-time
  // refresh приносить нові rows, count > baseline → progress complete.
  const [simulating, setSimulating] = useState(false);
  const [expanding, setExpanding] = useState(false);
  const simBaseline = useRef(narrativeVariants.length);
  const expandBaseline = useRef(variants.length);

  useEffect(() => {
    if (simulating && narrativeVariants.length > simBaseline.current) {
      setSimulating(false);
    }
  }, [narrativeVariants.length, simulating]);

  useEffect(() => {
    if (expanding && variants.length > expandBaseline.current) {
      setExpanding(false);
      // Auto-expand коли variants з'явилися щоб user одразу їх бачив.
      setExpanded(true);
    }
  }, [variants.length, expanding]);

  function onReview(status: "approved" | "rejected") {
    setOptimisticStatus(status);
    if (status === "approved") {
      expandBaseline.current = variants.length;
      setExpanding(true);
      setExpanded(true);
    }
    const t =
      status === "approved"
        ? toast.loading("Approve → expanding draft", {
            description: "W7 будує 3 channel variants (blog/X/LinkedIn)",
          })
        : toast.loading("Rejecting draft");
    startTransition(async () => {
      try {
        const result = await reviewCounterDraft({
          draft_id: draft.id,
          organization_id: organizationId,
          brand_slug: brandSlug,
          status,
        });
        if (result.ok) {
          toast.success(status === "approved" ? "Draft approved → expansion triggered" : "Draft rejected", {
            id: t,
            description: status === "approved" ? "Variants з'являться у ~90s" : undefined,
          });
        } else {
          toast.error("Review fail", {
            id: t,
            description: result.reason ?? "DB update failed",
          });
          setOptimisticStatus(draft.status);
        }
      } catch (err) {
        toast.error("Review fail", {
          id: t,
          description: err instanceof Error ? err.message : "unknown",
        });
        setOptimisticStatus(draft.status);
      }
    });
  }

  function onCopy() {
    navigator.clipboard
      .writeText(draft.body)
      .then(() => toast.success("Скопійовано у буфер"))
      .catch((err) => toast.error("Не вдалося скопіювати", { description: String(err) }));
  }

  function onUseVariant(variantId: string, rank: number) {
    setOptimisticStatus("approved");
    expandBaseline.current = variants.length;
    setExpanding(true);
    setExpanded(true);
    const t = toast.loading(`Using variant #${rank} → expanding`, {
      description: "Draft body заміняється на variant, W7 будує 3 channel versions",
    });
    startTransition(async () => {
      try {
        const result = await approveWithVariant({
          draft_id: draft.id,
          variant_id: variantId,
          organization_id: organizationId,
          brand_slug: brandSlug,
        });
        if (result.ok) {
          toast.success(`Variant #${rank} approved → expansion triggered`, {
            id: t,
            description: "Channel variants з'являться у ~90s",
          });
        } else {
          toast.error("Approve fail", { id: t, description: result.reason ?? "DB update failed" });
          setOptimisticStatus(draft.status);
        }
      } catch (err) {
        toast.error("Approve fail", {
          id: t,
          description: err instanceof Error ? err.message : "unknown",
        });
        setOptimisticStatus(draft.status);
      }
    });
  }

  function onPublish() {
    setOptimisticStatus("published");
    const t = toast.loading("Publishing to channels…", {
      description: "counter_draft → published, content_variants → sent",
    });
    startTransition(async () => {
      try {
        const result = await publishDraft({
          draft_id: draft.id,
          organization_id: organizationId,
          brand_slug: brandSlug,
        });
        if (result.ok) {
          toast.success("Published. Stepper closed.", {
            id: t,
            description: "Усі channel variants марковано як sent",
          });
        } else {
          toast.error("Publish fail", { id: t, description: result.reason ?? "DB update failed" });
          setOptimisticStatus(draft.status);
        }
      } catch (err) {
        toast.error("Publish fail", {
          id: t,
          description: err instanceof Error ? err.message : "unknown",
        });
        setOptimisticStatus(draft.status);
      }
    });
  }

  function onSimulate() {
    simBaseline.current = narrativeVariants.length;
    setSimulating(true);
    setExpanded(true);
    const t = toast.loading("Simulating alternatives", {
      description: "W5 ranking 3 variants по mention rate × position × sentiment",
    });
    startTransition(async () => {
      try {
        const result = await triggerSimulator({
          organization_id: organizationId,
          brand_slug: brandSlug,
          seed_type: "competitor-move",
          seed_payload: { counter_draft_id: draft.id, signal_id: draft.signal_id },
          requested_by: null,
          num_variants: 3,
        });
        if (result.ok) {
          toast.success("Simulator triggered", {
            id: t,
            description: "Variants з'являться у Simulator outputs за ~60s",
          });
        } else {
          toast.error("Simulator fail", { id: t, description: result.reason ?? "event API error" });
        }
      } catch (err) {
        toast.error("Simulator fail", {
          id: t,
          description: err instanceof Error ? err.message : "unknown",
        });
      }
    });
  }

  return (
    <li className={`rounded-md border border-border bg-background p-3 ${decided ? "opacity-70" : ""}`}>
      <button
        type="button"
        onClick={() => setExpanded((v) => !v)}
        aria-expanded={expanded}
        aria-controls={`draft-body-${draft.id}`}
        className="-m-1 flex w-full items-baseline justify-between gap-3 rounded p-1 text-left hover:bg-muted/30"
      >
        <div className="flex min-w-0 flex-wrap items-center gap-2">
          <span aria-hidden className="text-xs text-muted-foreground">
            {expanded ? "▾" : "▸"}
          </span>
          {signal ? (
            <span
              title={`signal severity: ${signal.severity}`}
              className={`inline-block h-2 w-2 shrink-0 rounded-full ${
                signal.severity === "high"
                  ? "bg-red-500"
                  : signal.severity === "med"
                  ? "bg-amber-500"
                  : "bg-zinc-400"
              }`}
            />
          ) : null}
          <span
            className={`rounded px-1.5 py-0.5 text-[10px] font-semibold uppercase ${statusColor[optimisticStatus]}`}
          >
            {optimisticStatus}
          </span>
          <span className="rounded bg-secondary px-1.5 py-0.5 text-[10px] text-secondary-foreground">
            {draft.channel_hint}
          </span>
          {!expanded ? (
            <span className="line-clamp-1 min-w-0 text-xs text-muted-foreground">
              {draft.body.slice(0, 120)}
            </span>
          ) : (
            <span className="text-xs text-muted-foreground">tone: {draft.tone_pillar}</span>
          )}
        </div>
        <span className="shrink-0 text-xs text-muted-foreground">
          {formatRelative(draft.created_at)}
        </span>
      </button>

      {!expanded ? null : (
        <div id={`draft-body-${draft.id}`}>
          {(simulating || expanding) ? (
            <div className="mt-2 flex items-center gap-2 rounded-md border border-primary/30 bg-primary/5 p-2 text-xs">
              <span className="inline-block h-2 w-2 animate-pulse rounded-full bg-primary" />
              <span className="font-medium">
                {simulating
                  ? "Simulating 3 alternatives…"
                  : "Expanding into 3 channels…"}
              </span>
              <span className="text-muted-foreground">~60-90s · UI auto-refresh</span>
            </div>
          ) : null}

          {signal ? (
            <a
              href={`?tab=signals#signal-${signal.id}`}
              className="mt-2 block rounded-md border border-border bg-muted/30 p-2 text-xs hover:bg-muted/50 transition-colors"
              title="View signal у Signals tab"
            >
              <div className="flex flex-wrap items-center gap-1.5">
                <span className="text-[10px] uppercase tracking-wider text-muted-foreground">
                  triggered by
                </span>
                <span
                  className={`rounded px-1.5 py-0.5 text-[10px] font-semibold uppercase ${severityChip[signal.severity]}`}
                >
                  {signal.severity}
                </span>
                {(() => {
                  const meta = sourceMeta(signal.source_type);
                  return (
                    <span
                      className={`rounded px-1.5 py-0.5 text-[10px] font-medium ${meta.cls}`}
                      title={meta.tooltip}
                    >
                      {meta.emoji} {meta.label}
                    </span>
                  );
                })()}
                <span className="ml-auto text-[10px] text-muted-foreground hover:underline">
                  view in feed ↗
                </span>
              </div>
              <p className="mt-1 line-clamp-2">{signal.summary}</p>
            </a>
          ) : null}

          <DraftStepper status={optimisticStatus} variantsCount={variants.length} />

          <p className="mt-2 whitespace-pre-wrap text-sm">{draft.body}</p>

      {draft.evidence_refs.length > 0 ? (
        <details className="mt-2 text-xs">
          <summary className="cursor-pointer text-muted-foreground hover:underline">
            Evidence ({draft.evidence_refs.length})
          </summary>
          <ul className="mt-1 space-y-0.5 pl-3">
            {draft.evidence_refs.map((ref, i) => (
              <li key={i} className="break-all">
                {ref.startsWith("http") ? (
                  <a href={ref} target="_blank" rel="noopener noreferrer" className="underline hover:text-foreground">
                    {ref.replace(/^https?:\/\//, "").slice(0, 80)}
                  </a>
                ) : (
                  <span className="font-mono text-muted-foreground">{ref}</span>
                )}
              </li>
            ))}
          </ul>
        </details>
      ) : null}

      {!decided && optimisticStatus === "draft" ? (
        <div className="mt-3 flex flex-col gap-2 sm:flex-row sm:flex-wrap">
          <Button size="sm" onClick={() => onReview("approved")} disabled={isPending}>
            ✓ Approve → 3 channels
          </Button>
          <Button size="sm" variant="outline" onClick={() => onReview("rejected")} disabled={isPending}>
            ✗ Reject
          </Button>
          <Button size="sm" variant="ghost" onClick={onCopy}>
            ⧉ Copy
          </Button>
          <Button size="sm" variant="ghost" onClick={onSimulate} disabled={isPending}>
            ↻ Simulate alternatives
          </Button>
        </div>
      ) : null}

      {narrativeVariants.length > 0 ? (
        <details className="mt-3 rounded-md border border-border bg-muted/30 p-2 text-xs" open>
          <summary className="cursor-pointer font-semibold text-muted-foreground hover:text-foreground">
            ↻ {narrativeVariants.length} simulator variants — обери, щоб запустити expansion
          </summary>
          <ol className="mt-2 space-y-2">
            {narrativeVariants
              .slice()
              .sort((a, b) => a.rank - b.rank)
              .map((v) => (
                <li key={v.id} className="rounded bg-background p-2">
                  <div className="flex flex-wrap items-baseline justify-between gap-2">
                    <div className="flex flex-wrap items-center gap-2">
                      <span className="rounded-full bg-primary/10 px-2 py-0.5 text-[10px] font-semibold text-primary">
                        #{v.rank}
                      </span>
                      {typeof v.metadata?.judge_score === "number" ? (
                        <span
                          className="font-medium"
                          title={v.metadata.judge_reasoning ?? ""}
                        >
                          judge {v.metadata.judge_score}/10
                        </span>
                      ) : (
                        <span className="font-medium">
                          score {v.score.toFixed(2)}
                        </span>
                      )}
                      <span title={`predicted sentiment: ${v.predicted_sentiment}`}>
                        {sentimentEmoji[v.predicted_sentiment]}
                      </span>
                      {v.metadata?.angle_label ? (
                        <span
                          title={`Angle: ${v.metadata.angle_label}`}
                          className="rounded bg-indigo-100 px-1.5 py-0.5 text-[10px] text-indigo-800 dark:bg-indigo-950 dark:text-indigo-300"
                        >
                          ∠ {v.metadata.angle_label}
                        </span>
                      ) : null}
                      {typeof v.metadata?.lift_vs_baseline === "number" ? (
                        <span
                          title="mention rate − Peec baseline visibility (legacy)"
                          className={`rounded px-1.5 py-0.5 text-[10px] ${
                            v.metadata.lift_vs_baseline >= 0
                              ? "bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300"
                              : "bg-zinc-100 text-zinc-700 dark:bg-zinc-800 dark:text-zinc-300"
                          }`}
                        >
                          {v.metadata.lift_vs_baseline >= 0 ? "▲" : "▼"} lift{" "}
                          {(v.metadata.lift_vs_baseline * 100).toFixed(0)}%
                        </span>
                      ) : null}
                      {v.metadata?.phrase_availability?.taken ? (
                        <span
                          title={`Used by: ${v.metadata.phrase_availability.by.join(", ")}`}
                          className="rounded bg-amber-100 px-1.5 py-0.5 text-[10px] text-amber-800 dark:bg-amber-950 dark:text-amber-300"
                        >
                          ⚠ phrase used by{" "}
                          {v.metadata.phrase_availability.by.slice(0, 2).join(", ")}
                        </span>
                      ) : null}
                      {v.metadata?.forbidden_retry_count ? (
                        <span
                          title="Variant was re-rolled once because the first attempt hit the brand voice forbidden-phrase ban"
                          className="rounded bg-amber-100 px-1.5 py-0.5 text-[10px] text-amber-800 dark:bg-amber-950 dark:text-amber-300"
                        >
                          ↻ re-rolled
                        </span>
                      ) : null}
                    </div>
                    {v.metadata?.judge_dimensions ? (
                      <span
                        title="Judge sub-dimensions: specificity / brand voice / persuasiveness / differentiation"
                        className="font-mono text-[10px] text-muted-foreground"
                      >
                        spc {v.metadata.judge_dimensions.specificity}
                        {" · "}voice {v.metadata.judge_dimensions.brand_voice}
                        {" · "}pers {v.metadata.judge_dimensions.persuasiveness}
                        {" · "}diff {v.metadata.judge_dimensions.differentiation}
                      </span>
                    ) : (
                      <span className="text-[10px] text-muted-foreground">
                        mention {(v.mention_rate * 100).toFixed(0)}% · pos{" "}
                        {v.avg_position !== null ? v.avg_position.toFixed(1) : "—"}
                      </span>
                    )}
                  </div>
                  <p className="mt-1 whitespace-pre-wrap text-xs">{v.body}</p>
                  {v.metadata?.judge_reasoning ? (
                    <p className="mt-1 italic text-[11px] text-muted-foreground">
                      → {v.metadata.judge_reasoning}
                    </p>
                  ) : null}
                  {!decided && optimisticStatus === "draft" ? (
                    <Button
                      size="sm"
                      variant="outline"
                      className="mt-2"
                      onClick={() => onUseVariant(v.id, v.rank)}
                      disabled={isPending}
                    >
                      ✓ Use #{v.rank} & expand into 3 channels
                    </Button>
                  ) : null}
                </li>
              ))}
          </ol>
        </details>
      ) : null}

      {variants.length > 0 && optimisticStatus === "approved" && variants.every((v) => v.status !== "sent") ? (
        <div className="mt-3 flex flex-col gap-1 rounded-md border border-emerald-200 bg-emerald-50/50 p-2 text-xs dark:border-emerald-900 dark:bg-emerald-950/20 sm:flex-row sm:items-center sm:justify-between">
          <span className="text-muted-foreground">
            Усі 3 channel variants готові. Закриваємо loop?
          </span>
          <Button
            size="sm"
            onClick={onPublish}
            disabled={isPending}
            className="bg-emerald-600 text-white hover:bg-emerald-700"
          >
            📤 Publish to channels
          </Button>
        </div>
      ) : null}

      {variants.length > 0 ? (
        <div className="mt-3 rounded-md border border-border bg-muted/30 p-2 text-xs">
          <p className="mb-2 font-semibold text-muted-foreground">
            📤 {variants.length} channel variants (W7 expand · blog · X · LinkedIn) — клікни, щоб розгорнути
            {optimisticStatus === "published" || variants.every((v) => v.status === "sent") ? (
              <span className="ml-2 rounded bg-emerald-100 px-1.5 py-0.5 text-[10px] uppercase text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300">
                ✓ All sent
              </span>
            ) : null}
          </p>
          <ul className="space-y-1.5">
            {variants
              .slice()
              .sort((a, b) => a.channel.localeCompare(b.channel))
              .map((v) => (
                <li key={v.id}>
                  <details className="rounded bg-background">
                    <summary className="flex cursor-pointer flex-wrap items-baseline gap-2 p-2 hover:bg-muted/40 list-none">
                      <span className="font-semibold">{channelLabel(v.channel)}</span>
                      {v.title ? (
                        <span className="font-medium">{v.title}</span>
                      ) : null}
                      <span className="line-clamp-1 min-w-0 flex-1 text-muted-foreground">
                        {v.body.replace(/\s+/g, " ").slice(0, 80)}…
                      </span>
                      <span className="text-[10px] uppercase tracking-wider text-muted-foreground">
                        {v.body.length} chars
                      </span>
                    </summary>
                    <div className="border-t border-border p-2">
                      {v.title ? (
                        <p className="mb-1 font-medium">{v.title}</p>
                      ) : null}
                      <p className="whitespace-pre-wrap text-xs leading-relaxed">{v.body}</p>
                      <button
                        type="button"
                        onClick={() => {
                          navigator.clipboard.writeText(v.body).catch(() => {});
                          toast.success(`${channelLabel(v.channel)} скопійовано`);
                        }}
                        className="mt-2 text-[11px] text-muted-foreground hover:underline"
                      >
                        ⧉ Copy {channelLabel(v.channel)} body
                      </button>
                    </div>
                  </details>
                </li>
              ))}
          </ul>
        </div>
      ) : null}
        </div>
      )}
    </li>
  );
}
